  kvec.cpp
kvec.obj : error LNK2019: "public: __thiscall Kvector::Kvector(int,int)" (??0Kvector@@QAE@HH@Z)_main 함수에서 참조되는 확인할 수 없는 외부 기호
kvec.obj : error LNK2019: "public: __thiscall Kvector::Kvector(class Kvector const &)" (??0Kvector@@QAE@ABV0@@Z)_main 함수에서 참조되는 확인할 수 없는 외부 기호
C:\Users\jcjin\Desktop\C++\kvec\Debug\kvec.exe : fatal error LNK1120: 2개의 확인할 수 없는 외부 참조입니다.
